//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Highstock_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandlestickVolume
    {
        public int Id { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<int> Open { get; set; }
        public Nullable<int> High { get; set; }
        public Nullable<int> Low { get; set; }
        public Nullable<int> Close { get; set; }
        public Nullable<long> Volume { get; set; }
    }
}
