//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HighstockDataEntities : DbContext
    {
        public HighstockDataEntities()
            : base("name=HighstockDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppleData> AppleDatas { get; set; }
        public DbSet<CandlestickVolume> CandlestickVolumes { get; set; }
        public DbSet<DataGrouping> DataGroupings { get; set; }
        public DbSet<Flag> Flags { get; set; }
        public DbSet<GoogleData> GoogleDatas { get; set; }
        public DbSet<Intraday> Intradays { get; set; }
        public DbSet<MicrosoftData> MicrosoftDatas { get; set; }
    }
}
